In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,r2_score
from sklearn.ensemble import RandomForestClassifier

In [9]:
df=pd.read_csv('fruits.csv')
df.head()

   size (cm)  shape  weight (g)  avg_price (₹)   color  taste     fruit_name
0       25.4  round      3089.2          137.1   green  sweet     watermelon
1       24.6  round      3283.9          163.8   green  sweet     watermelon
2        7.8  round       319.0           91.3   green  sweet  custard apple
3       20.0   oval      1607.0           85.7  orange  sweet         papaya
4       10.2   long       131.5           37.8  yellow  sweet         banana

In [10]:
df.describe()

          size (cm)    weight (g)  avg_price (₹)
count  10000.000000  10000.000000   10000.000000
mean       8.430600    455.457720      77.016720
std        6.396915    731.643087      38.946916
min        0.900000      4.500000       9.000000
25%        3.700000     45.800000      45.575000
50%        7.200000    168.800000      75.400000
75%       10.100000    365.275000     100.700000
max       27.500000   3299.800000     165.000000

In [11]:
df.dtypes

size (cm)        float64
shape             object
weight (g)       float64
avg_price (₹)    float64
color             object
taste             object
fruit_name        object
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   size (cm)      10000 non-null  float64
 1   shape          10000 non-null  object
 2   weight (g)     10000 non-null  float64
 3   avg_price (₹)  10000 non-null  float64
 4   color          10000 non-null  object
 5   taste          10000 non-null  object
 6   fruit_name     10000 non-null  object
dtypes: float64(3), object(4)
memory usage: 547.0+ KB

In [13]:
df.shape

(10000, 7)

In [14]:
df.isna().any()

size (cm)        False
shape            False
weight (g)       False
avg_price (₹)    False
color            False
taste            False
fruit_name       False
dtype: bool

In [15]:
leb=LabelEncoder()

In [18]:
df['shape']=leb.fit_transform(df['shape'])

df['color']=leb.fit_transform(df['color'])

df['taste']=leb.fit_transform(df['taste'])

df['fruit_name']=leb.fit_transform(df['fruit_name'])

In [20]:
df.head(20)

    size (cm)  shape  weight (g)  avg_price (₹)  color  taste  fruit_name
0        25.4      2      3089.2          137.1      2      1          19
1        24.6      2      3283.9          163.8      2      1          19
2         7.8      2       319.0           91.3      2      1           5
3        20.0      1      1607.0           85.7      3      1          13
4        10.2      0       131.5           37.8      7      1           1
5        19.4      1      1404.1           86.0      3      1          13
6         6.3      2       262.3          125.0      6      1          17
7         0.9      2         5.4            9.4      5      1           7
8         4.0      2        46.4           66.9      5      2          16
9         7.6      2       274.7           93.0      2      1           5
10        7.3      2       213.3           65.5      2      0           8
11        1.0      2         5.1           38.0      0      1           2
12       18.9      2      1212.2          101.1      1      1           4
13        3.0      1         9.7           31.8      6      1           3
14        8.5      1       260.3          110.3      7      1          11
15       16.9      2      1123.6          109.4      1      1           4
16        6.7      2       242.3          127.2      6      1          17
17        9.2      1       249.3          121.9      7      1          11
18        7.5      2       195.4           56.7      2      0           8
19       15.1      1      1305.2           98.6      1      2          15

In [21]:
x=df.drop('fruit_name',axis=1)
y=df['fruit_name']

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# random_state deermines the reproducibility of the splitting

In [29]:
#creating the model. if you fail to bring the n_estimators, it is still going to be 100
model=RandomForestClassifier(random_state=42)

In [30]:
model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [32]:
y_pred=model.predict(x_test)
y_pred

array([17,  0, 17, ..., 12, 14, 10], shape=(2000,))

In [33]:
model.score(x_test,y_test)

1.0

In [49]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0

In [50]:
classificationReport=classification_report(y_test,y_pred)
print(classificationReport)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        99
           1       1.00      1.00      1.00       103
           2       1.00      1.00      1.00       116
           3       1.00      1.00      1.00        89
           4       1.00      1.00      1.00       111
           5       1.00      1.00      1.00        99
           6       1.00      1.00      1.00        96
           7       1.00      1.00      1.00       115
           8       1.00      1.00      1.00        84
           9       1.00      1.00      1.00        96
          10       1.00      1.00      1.00       107
          11       1.00      1.00      1.00        87
          12       1.00      1.00      1.00        89
          13       1.00      1.00      1.00        96
          14       1.00      1.00      1.00       106
          15       1.00      1.00      1.00        93
          16       1.00      1.00      1.00       104
          17       1.00      1.00      1.00       119
          18       1.00      1.00      1.00        73
          19       1.00      1.00      1.00       118

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [51]:
new_fruit=[[25.0,1,1670,140,0,0]]
new_pred=model.predict(new_fruit)

C:\Users\PATHWAY\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [52]:
fruit=leb.inverse_transform(y_pred)
print(fruit)

[17  0 17 ... 12 14 10]